### ISSUE TITLE
cinema time 1 has new link

### ISSUE THREAD

**Issue by jimgate07** [azgaresncf/strm2hls#104]
https://www.twitch.tv/cinematimetv1

**Comment by azgaresncf** [comment]
### **are you sure that these channels are even legal?**
![image](https://github.com/azgaresncf/strm2hls/assets/50982832/98ac625e-e5aa-44ae-993e-4bb635c4f165)
_This channel is currently unavailable due to a violation of the Community Guidelines or Twitch Terms of Use._

**Comment by azgaresncf** [comment]
@jimgate07 could you please contact me on Discord? https://discord.com/users/817817254187892767 (or @azgaresncf)
