### ISSUE TITLE
dont work

### ISSUE THREAD

**Issue by gio299** [azgaresncf/strm2hls#109]
#EXTINF:-1, Star Kentrikis Eladas Greece
https://raw.githubusercontent.com/azgaresncf/strm2hls/main/streams/Star_Kentrikis_Eladas_Greece.m3u8

#EXTINF:-1, Euronews (Greece)
https://raw.githubusercontent.com/azgaresncf/strm2hls/main/streams/Euronews_Greece.m3u8

stop to grab links from dailymotion

**Comment by jimgate07** [comment]
I don't know why you removed them from the main list. The channels are working perfectly.
