### ISSUE TITLE
Add: Red Uno (Bolivia)

### ISSUE THREAD

**Issue by GiovanniSebastian** [azgaresncf/strm2hls#11]
Red Uno Signals...

Santa Cruz: https://www.dailymotion.com/video/x825whp
La Paz: https://www.dailymotion.com/video/x8ko1ix
Cochabamba: https://www.dailymotion.com/video/x827j2y

**Comment by azgaresncf** [comment]
closed with [this commit](https://github.com/azgaresncf/strm2hls/commit/a7ee4a94b7afe18d1bb91c0503002589daa24d00)

**Comment by azgaresncf** [comment]
closed with [this commit](https://github.com/azgaresncf/strm2hls/commit/a7ee4a94b7afe18d1bb91c0503002589daa24d00)
