### ISSUE TITLE
Fix: elocho TV Tucumán

### ISSUE THREAD

**Issue by GiovanniSebastian** [azgaresncf/strm2hls#118]
Stream Link: https://www.dailymotion.com/video/x8z8w7c
Source: https://www.elocho.tv/el-ocho-en-vivo.html

**Comment by azgaresncf** [comment]
already fixed

**Comment by azgaresncf** [comment]
![image](https://github.com/user-attachments/assets/2aa9d950-028d-4982-9992-f68ed29f0c44)
