### ISSUE TITLE
Dion Kentrikis

### ISSUE THREAD

**Issue by tolisnas** [azgaresncf/strm2hls#119]
Hello -  Can you please add the below?  
https://www.twitch.tv/diontvkmakedonias

I guess the name changed and you used to have it as per below
https://github.com/azgaresncf/strm2hls/blob/main/streams/DionTvKentrikisMakedonias.m3u8

**Comment by azgaresncf** [comment]
i will add it asap, dw

**Comment by trikalinos** [comment]
Thanks. You can just replace the existing one DionTvKentrikisMakedonias with diontvkmadedonias
