### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by gio299** [azgaresncf/strm2hls#120]
This stream change every 4 stunde.
I need to grab streams every time  please !
https://www.arttv.info/p/art.html
Thanks azgaresncf !1

**Comment by azgaresncf** [comment]
Hi,
I cannot grab streams every time, it is impossible. I have to wait a bit because otherwise the stream will expire out.

**Comment by gio299** [comment]
ok we need to grab streams every 5 Std.
https://www.arttv.info/p/art.html
