### ISSUE TITLE
Add: Telefe (Twitch)

### ISSUE THREAD

**Issue by GiovanniSebastian** [azgaresncf/strm2hls#132]
Stream Link: https://www.twitch.tv/telefe

**Comment by azgaresncf** [comment]
offline

**Comment by GiovanniSebastian** [comment]
*Broadcasts at various times.

**Comment by GiovanniSebastian** [comment]
I suggested these links because they are from official podcasts and television channels (except Gogoplay and Alf's) where faces from these channels react to the programs they broadcast. So in practice, it is an alternative to watch the programs from these channels without needing the usual stream (which are often geo-blocked).
