### ISSUE TITLE
Add: ATB (Bolivia)

### ISSUE THREAD

**Issue by FrancoSantosTV** [azgaresncf/strm2hls#17]
ATB (Santa Cruz): https://www.dailymotion.com/video/x84t82c
ATB (La Paz): https://www.dailymotion.com/video/x84eirw
ATB (Cochabamba): https://www.dailymotion.com/video/x89sfvo

**Comment by FrancoSantosTV** [comment]
I suggest changing the channel names in this issue: #11

Red Uno (Santa Cruz)
Red Uno (La Paz)
Red Uno (Cochabamba)

**Comment by azgaresncf** [comment]
done with [this commit](https://github.com/azgaresncf/strm2hls/commit/3d1cd96bd772a7e4c862c970d3deb1248a86a739)
