### ISSUE TITLE
add channels

### ISSUE THREAD

**Issue by gio299** [azgaresncf/strm2hls#41]
https://www.twitch.tv/livethess
https://www.twitch.tv/verginachannel
https://www.twitch.tv/centertv
https://www.twitch.tv/tvrodopi
https://www.twitch.tv/tvstarfm
https://www.twitch.tv/eurochannel
https://www.twitch.tv/diontvkentrikismakedonias
https://www.twitch.tv/flashtvgr
https://www.twitch.tv/lepantotv

**Comment by azgaresncf** [comment]
they will be added asap

**Comment by azgaresncf** [comment]
eurochannel is currently offline, it will be added later

**Comment by gio299** [comment]
Hi !
i thing
https://raw.githubusercontent.com/azgaresncf/strm2hls/main/streams/DionTvKentrikisMakedonias.m3u8
not working!

Στις Δευ 30 Οκτ 2023 στις 1:04 μ.μ., ο/η Azgar ***@***.***>
έγραψε:
