### ISSUE TITLE
add channels

### ISSUE THREAD

**Issue by gio299** [azgaresncf/strm2hls#45]
https://www.twitch.tv/tvkosmosgr
https://www.twitch.tv/topchannelkozani
https://www.twitch.tv/astratv2021
https://www.twitch.tv/pronewstv

its better to grab  the links every 1 or 2 hours ,because the twitch change the links every 5 hours or 6 hours!
Thanks a lot!

**Comment by azgaresncf** [comment]
Thanks to you as well!
I will add the channels ASAP, because I can't right now.
Or you can do a PR if you want to!
