### ISSUE TITLE
Add Cartoon Channels

### ISSUE THREAD

**Issue by jimgate07** [azgaresncf/strm2hls#76]
https://www.twitch.tv/popelulz  cartoon tv 1
https://www.twitch.tv/rythmic_portal cartoon tv 2 
https://www.twitch.tv/pdcagbfhiceoiladq cartoon tv 3
https://www.twitch.tv/silly_tunes looney tunes 1
https://www.twitch.tv/bashimusprime retro cartoons

**Comment by azgaresncf** [comment]
are you sure that those channels aren't illegal?

**Comment by jimgate07** [comment]
Hello, multiple tv apps they are using them but u dont know if they are legal or not. You can just ignore them. Στις 19 Ιαν 2024 10:20, ο χρήστης Azgar ***@***.***> έγραψε:
are you sure that those channels aren't illegal?
