### ISSUE TITLE
check the streams not working

### ISSUE THREAD

**Issue by gio299** [azgaresncf/strm2hls#85]
https://raw.githubusercontent.com/azgaresncf/strm2hls/main/streams/Astra_TV.m3u8
https://raw.githubusercontent.com/azgaresncf/strm2hls/main/streams/thessaliatv.m3u8
https://raw.githubusercontent.com/azgaresncf/strm2hls/main/streams/Star_Kentrikis_Eladas_Greece.m3u8
https://raw.githubusercontent.com/azgaresncf/strm2hls/main/streams/tvstarfm.m3u8
https://raw.githubusercontent.com/azgaresncf/strm2hls/main/streams/LePanto.m3u8
https://raw.githubusercontent.com/azgaresncf/strm2hls/main/streams/DionTvKentrikisMakedonias.m3u8
https://raw.githubusercontent.com/azgaresncf/strm2hls/main/streams/CinemaTime2.m3u8

**Comment by azgaresncf** [comment]
astra https://github.com/azgaresncf/strm2hls/commit/369867f9628de834c8ae658b4a435cec7c70a760
thessalia https://github.com/azgaresncf/strm2hls/commit/7b985a97717b75d44f591ad5ad842c2e285d57cc
star kentrikis eldas https://github.com/azgaresncf/strm2hls/commit/6526f5fb4fb1ed88ad47a868f27ba9157decb157
tvstarfm https://github.com/azgaresncf/strm2hls/commit/5cfc12653e2d3efc48ee2b776359caf4f27cb1e9
LePanto https://github.com/azgaresncf/strm2hls/commit/6d021233862df2f68c9d1ce8e8d75649b77deae3
DionTvKentrikisMakedonias https://github.com/azgaresncf/strm2hls/commit/b632166e1ed03d246c3af44433124634efb3ef19
CinemaTime2 https://github.com/azgaresncf/strm2hls/commit/1a9dd90fce5f7834c17956df429ff15cdde070cb
