### ISSUE TITLE
fix 

### ISSUE THREAD

**Issue by gio299** [azgaresncf/strm2hls#86]
dailymotion streams and twitch streams working only a few hours,and then, we  must wait some hours to grab a new stream!

Can you fix it please?

**Comment by azgaresncf** [comment]
how many (approximate) hours do they stay online?

**Comment by gio299** [comment]
about 4 hours only

**Comment by gio299** [comment]
Azgaresncf hi !
The same problem continues !
We dont have update link for...

https://raw.githubusercontent.com/azgaresncf/strm2hls/main/streams/DionTVKentrikisMakedonias.m3u8
https://raw.githubusercontent.com/azgaresncf/strm2hls/main/streams/verginachannel.m3u8
https://raw.githubusercontent.com/azgaresncf/strm2hls/main/streams/tvioniathessalonikis.m3u8
https://raw.githubusercontent.com/azgaresncf/strm2hls/main/streams/centertv.m3u8

**Comment by azgaresncf** [comment]
it is because of this error
![error](https://github.com/azgaresncf/strm2hls/assets/50982832/07886ab0-d2bd-4097-9873-d4c1da1d8f5e)
